// all 50 rsc quests as a bot-driveable table (generated by generate-quests-data.js).
// fields: key, name, category (talk/combat/object), giverId, hub, qp, rewards, itemsNeeded, prereqs

module.exports = [
    {
        key: 'blackKnightsFortress',
        name: 'Black Knight\'s Fortress',
        category: 'object',
        giverId: 110, // Sir Amik Varze
        hub: { x: 305, y: 1507 },
        qp: 3,
        rewards: [],
        itemsNeeded: [],
        prereqs: { questPoints: 12 }
    },
    {
        key: 'cooksAssistant',
        name: 'Cook\'s Assistant',
        category: 'talk',
        giverId: 7, // cook
        hub: { x: 135, y: 661 },
        qp: 1,
        rewards: [{ skill: 'cooking', varXp: 200, baseXp: 1000 }],
        itemsNeeded: [{ id: 22, amount: 1 }, { id: 136, amount: 1 }, { id: 19, amount: 1 }],
        prereqs: {}
    },
    {
        key: 'demonSlayer',
        name: 'Demon Slayer',
        category: 'combat',
        giverId: 14, // Gypsy
        hub: { x: 135, y: 513 },
        bossId: 35, bossName: 'Delrith', boss: { x: 111, y: 550 },
        qp: 3,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'doricsQuest',
        name: 'Doric\'s Quest',
        category: 'talk',
        giverId: 144, // Doric
        hub: { x: 326, y: 488 },
        qp: 1,
        rewards: [{ skill: 'mining', varXp: 300, baseXp: 700 }],
        itemsNeeded: [{ id: 149, amount: 6 }, { id: 150, amount: 4 }, { id: 151, amount: 2 }],
        prereqs: {}
    },
    {
        key: 'theRestlessGhost',
        name: 'The Restless Ghost',
        category: 'object',
        giverId: 9, // Priest
        hub: { x: 111, y: 669 },
        qp: 1,
        rewards: [{ skill: 'prayer', varXp: 250, baseXp: 2000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'goblinDiplomacy',
        name: 'Goblin Diplomacy',
        category: 'talk',
        giverId: 150, // Bartender
        hub: { x: 255, y: 626 },
        qp: 5,
        rewards: [{ skill: 'crafting', varXp: 60, baseXp: 500 }],
        itemsNeeded: [{ id: 273, amount: 1 }],
        prereqs: {}
    },
    {
        key: 'ernestTheChicken',
        name: 'Ernest the Chicken',
        category: 'object',
        giverId: 36, // Veronica
        hub: { x: 208, y: 567 },
        qp: 4,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'impCatcher',
        name: 'Imp Catcher',
        category: 'talk',
        giverId: 117, // Wizard Mizgog
        hub: { x: 217, y: 2583 },
        qp: 1,
        rewards: [{ skill: 'magic', varXp: 400, baseXp: 1500 }],
        itemsNeeded: [{ id: 231, amount: 1 }, { id: 232, amount: 1 }, { id: 233, amount: 1 }, { id: 234, amount: 1 }],
        prereqs: {}
    },
    {
        key: 'piratesTreasure',
        name: 'Pirate\'s Treasure',
        category: 'object',
        giverId: 128, // Redbeard Frank
        hub: { x: 251, y: 631 },
        qp: 2,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'princeAliRescue',
        name: 'Prince Ali Rescue',
        category: 'object',
        giverId: 119, // Hassan
        hub: { x: 67, y: 697 },
        qp: 3,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'romeoAndJuliet',
        name: 'Romeo & Juliet',
        category: 'talk',
        giverId: 30, // Romeo
        hub: { x: 133, y: 508 },
        qp: 5,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'sheepShearer',
        name: 'Sheep Shearer',
        category: 'talk',
        giverId: 77, // Fred the farmer
        hub: { x: 160, y: 619 },
        qp: 1,
        rewards: [{ skill: 'crafting', varXp: 100, baseXp: 500 }],
        itemsNeeded: [{ id: 207, amount: 20 }],
        prereqs: {}
    },
    {
        key: 'shieldOfArrav',
        name: 'Shield of Arrav',
        category: 'object',
        giverId: 20, // Reldo
        hub: { x: 131, y: 455 },
        qp: 1,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'theKnightsSword',
        name: 'The Knight\'s Sword',
        category: 'object',
        giverId: 132, // squire
        hub: { x: 311, y: 568 },
        qp: 1,
        rewards: [{ skill: 'smithing', varXp: 1500, baseXp: 1400 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'vampireSlayer',
        name: 'Vampire Slayer',
        category: 'combat',
        giverId: 97, // Morgan
        hub: { x: 217, y: 618 },
        bossId: 96, bossName: 'Count Draynor',
        qp: 3,
        rewards: [{ skill: 'attack', varXp: 600, baseXp: 1300 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'witchsPotion',
        name: 'Witch\'s Potion',
        category: 'object',
        giverId: 148, // Hetty
        hub: { x: 317, y: 667 },
        qp: 1,
        rewards: [{ skill: 'magic', varXp: 200, baseXp: 900 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'dragonSlayer',
        name: 'Dragon Slayer',
        category: 'combat',
        giverId: 111, // Guildmaster
        hub: { x: 151, y: 555 },
        bossId: 196, bossName: 'Dragon', boss: { x: 418, y: 3479 },
        qp: 2,
        rewards: [{ skill: 'strength', varXp: 1200, baseXp: 2600 }, { skill: 'defense', varXp: 1200, baseXp: 2600 }],
        itemsNeeded: [],
        prereqs: { questPoints: 32 }
    },
    {
        key: 'witchsHouse',
        name: 'Witch\'s House',
        category: 'object',
        giverId: 240, // Boy
        hub: { x: 357, y: 489 },
        qp: 4,
        rewards: [{ skill: 'hits', varXp: 600, baseXp: 1300 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'lostCity',
        name: 'Lost City',
        category: 'object',
        giverId: 207, // Adventurer
        hub: { x: 178, y: 667 },
        qp: 3,
        rewards: [],
        itemsNeeded: [],
        prereqs: { skills: [{ skill: 'woodcutting', level: 36 }, { skill: 'crafting', level: 31 }] }
    },
    {
        key: 'herosQuest',
        name: 'Heroes\' Quest',
        category: 'object',
        giverId: 253, // Achetties
        hub: { x: 372, y: 443 },
        qp: 1,
        rewards: [{ skill: 'strength', varXp: 200, baseXp: 300 }, { skill: 'defense', varXp: 200, baseXp: 300 }, { skill: 'hits', varXp: 200, baseXp: 300 }, { skill: 'attack', varXp: 200, baseXp: 300 }, { skill: 'ranged', varXp: 200, baseXp: 300 }, { skill: 'herblaw', varXp: 200, baseXp: 300 }, { skill: 'fishing', varXp: 200, baseXp: 300 }, { skill: 'cooking', varXp: 200, baseXp: 300 }, { skill: 'firemaking', varXp: 200, baseXp: 300 }, { skill: 'woodcutting', varXp: 200, baseXp: 300 }, { skill: 'mining', varXp: 200, baseXp: 300 }, { skill: 'smithing', varXp: 200, baseXp: 300 }],
        itemsNeeded: [],
        prereqs: { questPoints: 55, quests: ['lostCity', 'shieldOfArrav', 'merlinsCrystal', 'dragonSlayer'] }
    },
    {
        key: 'druidicRitual',
        name: 'Druidic Ritual',
        category: 'object',
        giverId: 204, // Kaqemeex
        hub: { x: 362, y: 459 },
        qp: 4,
        rewards: [{ skill: 'herblaw', varXp: 0, baseXp: 1000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'merlinsCrystal',
        name: 'Merlin\'s Crystal',
        category: 'object',
        giverId: 275, // King Arthur
        hub: { x: 474, y: 453 },
        qp: 6,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'scorpionCatcher',
        name: 'Scorpion Catcher',
        category: 'object',
        giverId: 300, // Thormac the sorceror
        hub: { x: 511, y: 1452 },
        qp: 1,
        rewards: [{ skill: 'strength', varXp: 500, baseXp: 1500 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'familyCrest',
        name: 'Family Crest',
        category: 'object',
        giverId: 309, // Dimintheis
        hub: { x: 84, y: 523 },
        qp: 1,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'tribalTotem',
        name: 'Tribal Totem',
        category: 'object',
        giverId: 330, // gem merchant
        hub: { x: 551, y: 598 },
        qp: 1,
        rewards: [{ skill: 'thieving', varXp: 300, baseXp: 800 }],
        itemsNeeded: [],
        prereqs: { skills: [{ skill: 'thieving', level: 21 }] }
    },
    {
        key: 'fishingContest',
        name: 'Fishing Contest',
        category: 'object',
        giverId: 355, // Mountain Dwarf
        hub: { x: 386, y: 471 },
        qp: 1,
        rewards: [{ skill: 'fishing', varXp: 300, baseXp: 900, bonusAt: 24, bonusXp: 800 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'monksFriend',
        name: 'Monk\'s Friend',
        category: 'object',
        giverId: 350, // Brother Omad
        hub: { x: 580, y: 665 },
        qp: 1,
        rewards: [{ skill: 'woodcutting', varXp: 500, baseXp: 500 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'templeOfIkov',
        name: 'Temple of Ikov',
        category: 'object',
        giverId: 360, // Lucien
        hub: { x: 615, y: 587 },
        qp: 1,
        rewards: [{ skill: 'ranged', varXp: 1000, baseXp: 2000 }, { skill: 'fletching', varXp: 1000, baseXp: 2000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'clockTower',
        name: 'Clock Tower',
        category: 'object',
        giverId: 366, // Brother Kojo
        hub: { x: 580, y: 637 },
        qp: 1,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'theHolyGrail',
        name: 'The Holy Grail',
        category: 'object',
        giverId: 275, // King Arthur
        hub: { x: 474, y: 453 },
        qp: 2,
        rewards: [{ skill: 'prayer', varXp: 1000, baseXp: 1000 }, { skill: 'defense', varXp: 1200, baseXp: 1200 }],
        itemsNeeded: [],
        prereqs: { quests: ['merlinsCrystal'] }
    },
    {
        key: 'fightArena',
        name: 'Fight Arena',
        category: 'combat',
        giverId: 372, // Lady servil
        hub: { x: 575, y: 679 },
        bossId: 388, bossName: 'Bouncer',
        qp: 2,
        rewards: [{ skill: 'attack', varXp: 800, baseXp: 700 }, { skill: 'thieving', varXp: 800, baseXp: 700 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'treeGnomeVillage',
        name: 'Tree Gnome Village',
        category: 'combat',
        giverId: 400, // bolren
        hub: { x: 648, y: 1635 },
        bossId: 410, bossName: 'khazard warlord', boss: { x: 671, y: 592 },
        qp: 2,
        rewards: [{ skill: 'attack', varXp: 900, baseXp: 800 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'theHazeelCult',
        name: 'The Hazeel Cult',
        category: 'object',
        giverId: 418, // ceril
        hub: { x: 613, y: 1562 },
        qp: 1,
        rewards: [{ skill: 'thieving', varXp: 200, baseXp: 2000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'sheepHerder',
        name: 'Sheep Herder',
        category: 'object',
        giverId: 436, // Councillor Halgrive
        hub: { x: 586, y: 606 },
        qp: 4,
        rewards: [],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'plagueCity',
        name: 'Plague City',
        category: 'object',
        giverId: 437, // Edmond
        hub: { x: 625, y: 3417 },
        qp: 1,
        rewards: [{ skill: 'mining', varXp: 300, baseXp: 700 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'seaSlug',
        name: 'Sea Slug',
        category: 'object',
        giverId: 455, // Caroline
        hub: { x: 521, y: 619 },
        qp: 1,
        rewards: [{ skill: 'fishing', varXp: 800, baseXp: 700 }],
        itemsNeeded: [],
        prereqs: { skills: [{ skill: 'firemaking', level: 30 }] }
    },
    {
        key: 'waterfallQuest',
        name: 'Waterfall Quest',
        category: 'object',
        giverId: 470, // Almera
        hub: { x: 656, y: 448 },
        qp: 1,
        rewards: [{ skill: 'attack', varXp: 900, baseXp: 1000 }, { skill: 'strength', varXp: 900, baseXp: 1000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'biohazard',
        name: 'Biohazard',
        category: 'object',
        giverId: 483, // Elena
        hub: { x: 605, y: 573 },
        qp: 3,
        rewards: [{ skill: 'thieving', varXp: 200, baseXp: 2000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'junglePotion',
        name: 'Jungle Potion',
        category: 'object',
        giverId: 515, // Wizard Frumscone
        hub: { x: 606, y: 3585 },
        qp: 1,
        rewards: [{ skill: 'herblaw', varXp: 500, baseXp: 1600 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'grandTree',
        name: 'The Grand Tree',
        category: 'object',
        giverId: 541, // King Narnode Shareen
        hub: { x: 417, y: 163 },
        qp: 5,
        rewards: [{ skill: 'agility', varXp: 1200, baseXp: 1600 }, { skill: 'attack', varXp: 1200, baseXp: 1600 }, { skill: 'magic', varXp: 200, baseXp: 600 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'shiloVillage',
        name: 'Shilo Village',
        category: 'object',
        giverId: 539, // Mosol
        hub: { x: 382, y: 852 },
        qp: 2,
        rewards: [{ skill: 'crafting', varXp: 500, baseXp: 500 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'undergroundPass',
        name: 'Underground Pass',
        category: 'object',
        giverId: 512, // king Lathas
        hub: { x: 613, y: 602 },
        qp: 5,
        rewards: [{ skill: 'agility', varXp: 200, baseXp: 2000 }, { skill: 'attack', varXp: 200, baseXp: 2000 }],
        itemsNeeded: [],
        prereqs: { quests: ['biohazard'] }
    },
    {
        key: 'observatoryQuest',
        name: 'Observatory Quest',
        category: 'object',
        giverId: 652, // Observatory Professor
        hub: { x: 715, y: 682 },
        qp: 2,
        rewards: [{ skill: 'crafting', varXp: 400, baseXp: 1000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'touristTrap',
        name: 'The Tourist Trap',
        category: 'object',
        giverId: 538, // Irena
        hub: { x: 64, y: 738 },
        qp: 2,
        rewards: [{ skill: 'fletching', varXp: 600, baseXp: 600 }, { skill: 'agility', varXp: 600, baseXp: 600 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'watchtower',
        name: 'Watchtower',
        category: 'object',
        giverId: 672, // Watchtower wizard
        hub: { x: 492, y: 3524 },
        qp: 4,
        rewards: [{ skill: 'magic', varXp: 1000, baseXp: 1000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'dwarfCannon',
        name: 'Dwarf Cannon',
        category: 'object',
        giverId: 771, // Dwarf commander
        hub: { x: 605, y: 467 },
        qp: 1,
        rewards: [{ skill: 'crafting', varXp: 200, baseXp: 1000 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'murderMystery',
        name: 'Murder Mystery',
        category: 'object',
        giverId: 747, // Guard
        hub: { x: 495, y: 418 },
        qp: 3,
        rewards: [{ skill: 'crafting', varXp: 150, baseXp: 750 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'digsite',
        name: 'Digsite',
        category: 'object',
        giverId: 723, // Examiner
        hub: { x: 20, y: 568 },
        qp: 2,
        rewards: [{ skill: 'mining', varXp: 1200, baseXp: 1200 }, { skill: 'herblaw', varXp: 500, baseXp: 500 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'gertrudesCat',
        name: 'Gertrude\'s Cat',
        category: 'object',
        giverId: 714, // Gertrude
        hub: { x: 161, y: 513 },
        qp: 1,
        rewards: [{ skill: 'cooking', varXp: 180, baseXp: 700 }],
        itemsNeeded: [],
        prereqs: {}
    },
    {
        key: 'legendsQuest',
        name: 'Legends Quest',
        category: 'object',
        giverId: 735, // Sir Radimus Erkle
        hub: { x: 517, y: 545 },
        qp: 4,
        rewards: [{ skill: 'attack', varXp: 600, baseXp: 600 }, { skill: 'strength', varXp: 600, baseXp: 600 }, { skill: 'defense', varXp: 600, baseXp: 600 }, { skill: 'hits', varXp: 600, baseXp: 600 }],
        itemsNeeded: [],
        prereqs: { questPoints: 107, quests: ['herosQuest', 'familyCrest', 'shiloVillage', 'undergroundPass', 'waterfallQuest'] }
    }
];
