// Dig Site (members) shared constants. ids taken straight from OpenRSC's raw
// ItemId/NpcId enum values, which are index-identical to rsc-data for the base range

// NPCs
const DIGSITE_GUIDE_ID = 726; // npcs[726] "Guide"
const ARCHAEOLOGICAL_EXPERT_ID = 728; // NpcId.ARCHAEOLOGICAL_EXPERT
const EXAMINER_ID = 723; // NpcId.EXAMINER
const STUDENT_ORANGE_ID = 727; // NpcId.STUDENT_ORANGE
const STUDENT_GREEN_ID = 725; // NpcId.STUDENT_GREEN
const STUDENT_PURPLE_ID = 724; // NpcId.STUDENT_PURPLE
const WORKMAN_ID = 722; // NpcId.WORKMAN
const WORKMAN_UNDERGROUND_ID = 738; // NpcId.WORKMAN_UNDERGROUND

// Items
const GOLD_NUGGETS_ID = 1118;
const GOLD_ID = 152;
const PANNING_TRAY_ID = 1111; // empty tray: search/take gold no-ops
const PANNING_TRAY_GOLD_NUGGET_ID = 1112; // tray holding a gold nugget find
const PANNING_TRAY_FULL_ID = 1113; // tray full of mud, ready to search
const CRACKED_ROCK_SAMPLE_ID = 1150;
const TALISMAN_OF_ZAROS_ID = 1175;
const DIGSITE_SCROLL_ID = 1173;
const UNIDENTIFIED_LIQUID_ID = 1232;
const NITROGLYCERIN_ID = 1161;
const UNIDENTIFIED_POWDER_ID = 1171;
const AMMONIUM_NITRATE_ID = 1160;
const MIXED_CHEMICALS_1_ID = 1178;
const EXPLOSIVE_COMPOUND_ID = 1176;
const MIXED_CHEMICALS_2_ID = 1180;
const STONE_TABLET_ID = 1174;
const GOLD_BAR_ID = 172;
const BELT_BUCKLE_ID = 1151;
const BONES_ID = 20;
const BROKEN_ARROW_ID = 1165;
const BROKEN_GLASS_DIGSITE_LVL_2_ID = 1170;
const BROKEN_STAFF_ID = 1167;
const BUTTONS_ID = 1166;
const CERAMIC_REMAINS_ID = 1169;
const DAMAGED_ARMOUR_1_ID = 1157;
const DAMAGED_ARMOUR_2_ID = 1158;
const NEEDLE_ID = 39;
const OLD_BOOT_ID = 1155;
const OLD_TOOTH_ID = 1162;
const ROCK_SAMPLE_GREEN_ID = 1117;
const ROCK_SAMPLE_ORANGE_ID = 1148;
const ROCK_SAMPLE_PURPLE_ID = 1149;
const ROTTEN_APPLES_ID = 801;
const RUSTY_SWORD_ID = 1159;
const VASE_ID = 1168;
const TROWEL_ID = 1145;
const UNSTAMPED_LETTER_OF_RECOMMENDATION_ID = 1147;
const STAMPED_LETTER_OF_RECOMMENDATION_ID = 1146;
const LEVEL_1_CERTIFICATE_ID = 1142;
const LEVEL_2_CERTIFICATE_ID = 1143;
const LEVEL_3_CERTIFICATE_ID = 1144;
const UNCUT_OPAL_ID = 891;
const UNCUT_JADE_ID = 890;
const UNCUT_SAPPHIRE_ID = 160;
const CUP_OF_TEA_ID = 739;
const ROPE_ID = 237;
const DIGSITE_CHEST_KEY_ID = 1164;
const SPECIMEN_JAR_ID = 1116;
const SPECIMEN_BRUSH_ID = 1115;
const ROCK_PICK_ID = 1114;
const SPADE_ID = 211;
const A_LUMP_OF_CHARCOAL_ID = 983;
const COINS_ID = 10;
const OPAL_ID = 894;
const COPPER_ORE_ID = 150;
const BROKEN_GLASS_ID = 778;
const PURPLEDYE_ID = 516;
const POT_ID = 135;
const CLAY_ID = 149;
const RATS_TAIL_ID = 271;
const JUG_ID = 140;
const BRONZE_SPEAR_ID = 827;
const PIE_DISH_ID = 251;
const IRON_THROWING_KNIFE_ID = 1075;
const MEDIUM_BLACK_HELMET_ID = 470;
const IRON_DAGGER_ID = 28;
const LEATHER_GLOVES_ID = 16;
const ICE_GLOVES_ID = 556;
const KLANKS_GAUNTLETS_ID = 1006;
const STEEL_GAUNTLETS_ID = 698;
const GAUNTLETS_OF_CHAOS_ID = 701;
const GAUNTLETS_OF_COOKING_ID = 700;
const GAUNTLETS_OF_GOLDSMITHING_ID = 699;
const BOOTS_ID = 17;
const EMPTY_VIAL_ID = 465;
const TINDERBOX_ID = 166;
const BOOK_OF_EXPERIMENTAL_CHEMISTRY_ID = 1141;
const BRONZE_PICKAXE_ID = 156;
const GROUND_CHARCOAL_ID = 1179;

// sentinel "you find nothing" items; null so nothing is added to the inventory
const NOTHING_ID = null;
const NOTHING_INTEREST_ID = null;

// Objects (scenery), raw OpenRSC object ids used directly
const WINCH_IDS = [1095, 1053]; // WINCH[0] @ (14,504), WINCH[1] @ (26,515)
const SOIL_IDS = [1065, 1066, 1067];
const ROCK_ID = 1059; // "Rocks", chip with a rockpick
const HOUSE_EAST_CHEST_CLOSED_ID = 1104;
const HOUSE_EAST_CHEST_OPEN_ID = 1105;
const HOUSE_EAST_CUPBOARD_CLOSED_ID = 1074;
const HOUSE_EAST_CUPBOARD_OPEN_ID = 1078;
const HOUSE_WEST_CHESTS_OPEN_ID = 17;
const HOUSE_WEST_CHESTS_CLOSED_ID = 18;
const TENT_CHEST_OPEN_ID = 1084;
const TENT_CHEST_LOCKED_ID = 1085;
const HOUSE_BOOKCASE_ID = 1090;
const SACKS_IDS = [1075, 1076]; // SACKS[1]=1076 holds the specimen jar
const BUSH_IDS = [1072, 1073]; // BUSH[1]=1073 holds the purple rock sample
const BURIED_SKELETON_IDS = [1057, 1049];
const SPECIMEN_TRAY_ID = 1052;
const CLIMB_UP_ROPE_SMALL_CAVE_ID = 1097; // -> (14,506)
const CLIMB_UP_ROPE_BIG_CAVE_ID = 1098; // -> (25,515)
const BRICK_ID = 1096; // underground, near (13-14, 3337)
const X_BARREL_ID = 1082;
const X_BARREL_OPEN_ID = 1083;
const SIGNPOST_IDS = [1060, 1061, 1062, 1063]; // training / lvl1 / lvl2 / lvl3
const PANNING_POINT_TYPE = 1058;

module.exports = {
    DIGSITE_GUIDE_ID,
    ARCHAEOLOGICAL_EXPERT_ID,
    EXAMINER_ID,
    STUDENT_ORANGE_ID,
    STUDENT_GREEN_ID,
    STUDENT_PURPLE_ID,
    WORKMAN_ID,
    WORKMAN_UNDERGROUND_ID,
    GOLD_NUGGETS_ID,
    GOLD_ID,
    PANNING_TRAY_ID,
    PANNING_TRAY_GOLD_NUGGET_ID,
    PANNING_TRAY_FULL_ID,
    CRACKED_ROCK_SAMPLE_ID,
    TALISMAN_OF_ZAROS_ID,
    DIGSITE_SCROLL_ID,
    UNIDENTIFIED_LIQUID_ID,
    NITROGLYCERIN_ID,
    UNIDENTIFIED_POWDER_ID,
    AMMONIUM_NITRATE_ID,
    MIXED_CHEMICALS_1_ID,
    EXPLOSIVE_COMPOUND_ID,
    MIXED_CHEMICALS_2_ID,
    STONE_TABLET_ID,
    GOLD_BAR_ID,
    BELT_BUCKLE_ID,
    BONES_ID,
    BROKEN_ARROW_ID,
    BROKEN_GLASS_DIGSITE_LVL_2_ID,
    BROKEN_STAFF_ID,
    BUTTONS_ID,
    CERAMIC_REMAINS_ID,
    DAMAGED_ARMOUR_1_ID,
    DAMAGED_ARMOUR_2_ID,
    NEEDLE_ID,
    OLD_BOOT_ID,
    OLD_TOOTH_ID,
    ROCK_SAMPLE_GREEN_ID,
    ROCK_SAMPLE_ORANGE_ID,
    ROCK_SAMPLE_PURPLE_ID,
    ROTTEN_APPLES_ID,
    RUSTY_SWORD_ID,
    VASE_ID,
    TROWEL_ID,
    UNSTAMPED_LETTER_OF_RECOMMENDATION_ID,
    STAMPED_LETTER_OF_RECOMMENDATION_ID,
    LEVEL_1_CERTIFICATE_ID,
    LEVEL_2_CERTIFICATE_ID,
    LEVEL_3_CERTIFICATE_ID,
    UNCUT_OPAL_ID,
    UNCUT_JADE_ID,
    UNCUT_SAPPHIRE_ID,
    CUP_OF_TEA_ID,
    ROPE_ID,
    DIGSITE_CHEST_KEY_ID,
    SPECIMEN_JAR_ID,
    SPECIMEN_BRUSH_ID,
    ROCK_PICK_ID,
    SPADE_ID,
    A_LUMP_OF_CHARCOAL_ID,
    COINS_ID,
    OPAL_ID,
    COPPER_ORE_ID,
    BROKEN_GLASS_ID,
    PURPLEDYE_ID,
    POT_ID,
    CLAY_ID,
    RATS_TAIL_ID,
    JUG_ID,
    BRONZE_SPEAR_ID,
    PIE_DISH_ID,
    IRON_THROWING_KNIFE_ID,
    MEDIUM_BLACK_HELMET_ID,
    IRON_DAGGER_ID,
    LEATHER_GLOVES_ID,
    ICE_GLOVES_ID,
    KLANKS_GAUNTLETS_ID,
    STEEL_GAUNTLETS_ID,
    GAUNTLETS_OF_CHAOS_ID,
    GAUNTLETS_OF_COOKING_ID,
    GAUNTLETS_OF_GOLDSMITHING_ID,
    BOOTS_ID,
    EMPTY_VIAL_ID,
    TINDERBOX_ID,
    BOOK_OF_EXPERIMENTAL_CHEMISTRY_ID,
    BRONZE_PICKAXE_ID,
    GROUND_CHARCOAL_ID,
    NOTHING_ID,
    NOTHING_INTEREST_ID,
    WINCH_IDS,
    SOIL_IDS,
    ROCK_ID,
    HOUSE_EAST_CHEST_CLOSED_ID,
    HOUSE_EAST_CHEST_OPEN_ID,
    HOUSE_EAST_CUPBOARD_CLOSED_ID,
    HOUSE_EAST_CUPBOARD_OPEN_ID,
    HOUSE_WEST_CHESTS_OPEN_ID,
    HOUSE_WEST_CHESTS_CLOSED_ID,
    TENT_CHEST_OPEN_ID,
    TENT_CHEST_LOCKED_ID,
    HOUSE_BOOKCASE_ID,
    SACKS_IDS,
    BUSH_IDS,
    BURIED_SKELETON_IDS,
    SPECIMEN_TRAY_ID,
    CLIMB_UP_ROPE_SMALL_CAVE_ID,
    CLIMB_UP_ROPE_BIG_CAVE_ID,
    BRICK_ID,
    X_BARREL_ID,
    X_BARREL_OPEN_ID,
    SIGNPOST_IDS,
    PANNING_POINT_TYPE
};
