// Dig Site constants

// NPCs (id-map.npcs)
const DIGSITE_GUIDE_ID = 726; // DIGSITE_GUIDE = npcs[726] Guide
const ARCHAEOLOGICAL_EXPERT_ID = 728; // NpcId.ARCHAEOLOGICAL_EXPERT
const EXAMINER_ID = 723; // NpcId.EXAMINER
const STUDENT_ORANGE_ID = 727; // NpcId.STUDENT_ORANGE
const STUDENT_GREEN_ID = 725; // NpcId.STUDENT_GREEN
const STUDENT_PURPLE_ID = 724; // NpcId.STUDENT_PURPLE
const WORKMAN_ID = 722; // NpcId.WORKMAN
const WORKMAN_UNDERGROUND_ID = 738; // NpcId.WORKMAN_UNDERGROUND

// Items (id-map.items)
const GOLD_NUGGETS_ID = 1118;
const GOLD_ID = 152;
const PANNING_TRAY_ID = 1111; // empty tray: search/take gold no-ops
const PANNING_TRAY_GOLD_NUGGET_ID = 1112; // tray holding a gold nugget find
const PANNING_TRAY_FULL_ID = 1113; // tray full of mud, ready to search
const CRACKED_ROCK_SAMPLE_ID = 1150;
const TALISMAN_OF_ZAROS_ID = 1175;
const DIGSITE_SCROLL_ID = 1173;
const UNIDENTIFIED_LIQUID_ID = 1232;
const NITROGLYCERIN_ID = 1161;
const UNIDENTIFIED_POWDER_ID = 1171;
const AMMONIUM_NITRATE_ID = 1160;
const MIXED_CHEMICALS_1_ID = 1178;
const EXPLOSIVE_COMPOUND_ID = 1176;
const MIXED_CHEMICALS_2_ID = 1180;
const STONE_TABLET_ID = 1174;
const GOLD_BAR_ID = 172;
const BELT_BUCKLE_ID = 1151;
const BONES_ID = 20;
const BROKEN_ARROW_ID = 1165;
const BROKEN_GLASS_DIGSITE_LVL_2_ID = 1170;
const BROKEN_STAFF_ID = 1167;
const BUTTONS_ID = 1166;
const CERAMIC_REMAINS_ID = 1169;
const DAMAGED_ARMOUR_1_ID = 1157;
const DAMAGED_ARMOUR_2_ID = 1158;
const NEEDLE_ID = 39;
const OLD_BOOT_ID = 1155;
const OLD_TOOTH_ID = 1162;
const ROCK_SAMPLE_GREEN_ID = 1117;
const ROCK_SAMPLE_ORANGE_ID = 1148;
const ROCK_SAMPLE_PURPLE_ID = 1149;
const ROTTEN_APPLES_ID = 801;
const RUSTY_SWORD_ID = 1159;
const VASE_ID = 1168;
const TROWEL_ID = 1145;
const UNSTAMPED_LETTER_OF_RECOMMENDATION_ID = 1147;
const STAMPED_LETTER_OF_RECOMMENDATION_ID = 1146;
const LEVEL_1_CERTIFICATE_ID = 1142;
const LEVEL_2_CERTIFICATE_ID = 1143;
const LEVEL_3_CERTIFICATE_ID = 1144;
const UNCUT_OPAL_ID = 891;
const UNCUT_JADE_ID = 890;
const UNCUT_SAPPHIRE_ID = 160;
const CUP_OF_TEA_ID = 739;
const ROPE_ID = 237;
const DIGSITE_CHEST_KEY_ID = 1164;
const SPECIMEN_JAR_ID = 1116;
const SPECIMEN_BRUSH_ID = 1115;
const ROCK_PICK_ID = 1114;
const SPADE_ID = 211;
const A_LUMP_OF_CHARCOAL_ID = 983;
const COINS_ID = 10;
const OPAL_ID = 894;
const COPPER_ORE_ID = 150;
const BROKEN_GLASS_ID = 778;
const PURPLEDYE_ID = 516;
const POT_ID = 135;
const CLAY_ID = 149;
const RATS_TAIL_ID = 271;
const JUG_ID = 140;
const BRONZE_SPEAR_ID = 827;
const PIE_DISH_ID = 251;
const IRON_THROWING_KNIFE_ID = 1075;
const MEDIUM_BLACK_HELMET_ID = 470;
const IRON_DAGGER_ID = 28;
const LEATHER_GLOVES_ID = 16;
const ICE_GLOVES_ID = 556;
const KLANKS_GAUNTLETS_ID = 1006;
const STEEL_GAUNTLETS_ID = 698;
const GAUNTLETS_OF_CHAOS_ID = 701;
const GAUNTLETS_OF_COOKING_ID = 700;
const GAUNTLETS_OF_GOLDSMITHING_ID = 699;
const BOOTS_ID = 17;
const EMPTY_VIAL_ID = 465;
const TINDERBOX_ID = 166;
const BOOK_OF_EXPERIMENTAL_CHEMISTRY_ID = 1141;
const BRONZE_PICKAXE_ID = 156;
const GROUND_CHARCOAL_ID = 1179;

// NOTHING / NOTHING_INTEREST: sentinel you-find-nothing items (null)
const NOTHING_ID = null;
const NOTHING_INTEREST_ID = null;

// Objects (obj-map: OpenRSC object id -> rsc type id). many collapse to one rsc type. PANNING_POINT 1058
const WINCH_TYPE = 1053; // WINCH {1095, 1053} both -> 1053
const SOIL_TYPE = 1065; // SOIL {1065, 1066, 1067} all -> 1065
const ROCK_TYPE = 164; // ROCK 1059 -> 164
const HOUSE_EAST_CHEST_TYPE = 17; // 1104/1105 -> 17 (all chests collide)
const HOUSE_EAST_CUPBOARD_TYPE = 56; // 1074/1078 -> 56
const HOUSE_WEST_CHESTS_TYPE = 17; // 17/18 -> 17
const TENT_CHEST_TYPE = 17; // 1084/1085 -> 17
const HOUSE_BOOKCASE_TYPE = 47; // 1090 -> 47
const SACKS_TYPE = 55; // {1075, 1076} -> 55
const BUSH_TYPE = 283; // {1072, 1073} -> 283
const BURIED_SKELETON_TYPE = 1049; // {1057, 1049} -> 1049
const SPECIMEN_TRAY_TYPE = 1052; // 1052 -> 1052
const CLIMB_UP_ROPE_TYPE = 1097; // {1097, 1098} -> 1097
const BRICK_TYPE = 1042; // 1096 -> 1042
const X_BARREL_TYPE = 22; // {1082, 1083} -> 22 (closed & open collide)
const SIGNPOST_TYPE = 61; // {1060..1063} -> 61
const PANNING_POINT_TYPE = 1058;

module.exports = {
    DIGSITE_GUIDE_ID,
    ARCHAEOLOGICAL_EXPERT_ID,
    EXAMINER_ID,
    STUDENT_ORANGE_ID,
    STUDENT_GREEN_ID,
    STUDENT_PURPLE_ID,
    WORKMAN_ID,
    WORKMAN_UNDERGROUND_ID,
    GOLD_NUGGETS_ID,
    GOLD_ID,
    PANNING_TRAY_ID,
    PANNING_TRAY_GOLD_NUGGET_ID,
    PANNING_TRAY_FULL_ID,
    CRACKED_ROCK_SAMPLE_ID,
    TALISMAN_OF_ZAROS_ID,
    DIGSITE_SCROLL_ID,
    UNIDENTIFIED_LIQUID_ID,
    NITROGLYCERIN_ID,
    UNIDENTIFIED_POWDER_ID,
    AMMONIUM_NITRATE_ID,
    MIXED_CHEMICALS_1_ID,
    EXPLOSIVE_COMPOUND_ID,
    MIXED_CHEMICALS_2_ID,
    STONE_TABLET_ID,
    GOLD_BAR_ID,
    BELT_BUCKLE_ID,
    BONES_ID,
    BROKEN_ARROW_ID,
    BROKEN_GLASS_DIGSITE_LVL_2_ID,
    BROKEN_STAFF_ID,
    BUTTONS_ID,
    CERAMIC_REMAINS_ID,
    DAMAGED_ARMOUR_1_ID,
    DAMAGED_ARMOUR_2_ID,
    NEEDLE_ID,
    OLD_BOOT_ID,
    OLD_TOOTH_ID,
    ROCK_SAMPLE_GREEN_ID,
    ROCK_SAMPLE_ORANGE_ID,
    ROCK_SAMPLE_PURPLE_ID,
    ROTTEN_APPLES_ID,
    RUSTY_SWORD_ID,
    VASE_ID,
    TROWEL_ID,
    UNSTAMPED_LETTER_OF_RECOMMENDATION_ID,
    STAMPED_LETTER_OF_RECOMMENDATION_ID,
    LEVEL_1_CERTIFICATE_ID,
    LEVEL_2_CERTIFICATE_ID,
    LEVEL_3_CERTIFICATE_ID,
    UNCUT_OPAL_ID,
    UNCUT_JADE_ID,
    UNCUT_SAPPHIRE_ID,
    CUP_OF_TEA_ID,
    ROPE_ID,
    DIGSITE_CHEST_KEY_ID,
    SPECIMEN_JAR_ID,
    SPECIMEN_BRUSH_ID,
    ROCK_PICK_ID,
    SPADE_ID,
    A_LUMP_OF_CHARCOAL_ID,
    COINS_ID,
    OPAL_ID,
    COPPER_ORE_ID,
    BROKEN_GLASS_ID,
    PURPLEDYE_ID,
    POT_ID,
    CLAY_ID,
    RATS_TAIL_ID,
    JUG_ID,
    BRONZE_SPEAR_ID,
    PIE_DISH_ID,
    IRON_THROWING_KNIFE_ID,
    MEDIUM_BLACK_HELMET_ID,
    IRON_DAGGER_ID,
    LEATHER_GLOVES_ID,
    ICE_GLOVES_ID,
    KLANKS_GAUNTLETS_ID,
    STEEL_GAUNTLETS_ID,
    GAUNTLETS_OF_CHAOS_ID,
    GAUNTLETS_OF_COOKING_ID,
    GAUNTLETS_OF_GOLDSMITHING_ID,
    BOOTS_ID,
    EMPTY_VIAL_ID,
    TINDERBOX_ID,
    BOOK_OF_EXPERIMENTAL_CHEMISTRY_ID,
    BRONZE_PICKAXE_ID,
    GROUND_CHARCOAL_ID,
    NOTHING_ID,
    NOTHING_INTEREST_ID,
    WINCH_TYPE,
    SOIL_TYPE,
    ROCK_TYPE,
    HOUSE_EAST_CHEST_TYPE,
    HOUSE_EAST_CUPBOARD_TYPE,
    HOUSE_WEST_CHESTS_TYPE,
    TENT_CHEST_TYPE,
    HOUSE_BOOKCASE_TYPE,
    SACKS_TYPE,
    BUSH_TYPE,
    BURIED_SKELETON_TYPE,
    SPECIMEN_TRAY_TYPE,
    CLIMB_UP_ROPE_TYPE,
    BRICK_TYPE,
    X_BARREL_TYPE,
    SIGNPOST_TYPE,
    PANNING_POINT_TYPE
};
